name: Security Audit
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Audit
        run: npm audit
